### deposit

POST http://127.0.0.1:5000/sample/deposit
Content-Type: application/json

{
    "id": "17",
    "amount": 12
}

### withdraw

POST http://127.0.0.1:5000/sample/withdraw
Content-Type: application/json

{ 
    "id": "17", 
    "amount": 5
}

###

//View Balance

GET http://127.0.0.1:5000/17
